name: terdin
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-126.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  faker: ^2.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts: 
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-SemiboldItalic.ttf

  assets: 
    - assets/images/man-1.png
    - assets/images/man-2.png
    - assets/images/man-3.png
    - assets/images/man-4.png
    - assets/images/man-5.png
    - assets/images/man-6.png
    - assets/images/man-7.png
    - assets/images/man-8.png
    - assets/images/man-9.png
    - assets/images/man-10.png
    - assets/images/man-11.png
    - assets/images/man-12.png
    - assets/images/man-13.png
    - assets/images/man-14.png
    - assets/images/man-15.png
    - assets/images/woman-1.png
    - assets/images/woman-2.png
    - assets/images/woman-3.png
    - assets/images/woman-4.png
    - assets/images/woman-5.png
    - assets/images/woman-6.png
    - assets/images/woman-7.png
    - assets/images/woman-8.png
    - assets/images/woman-9.png
    - assets/images/woman-10.png
    - assets/images/woman-11.png
    - assets/images/woman-12.png
    - assets/images/woman-13.png
    - assets/images/woman-14.png
    - assets/images/woman-15.png
    - assets/images/non-binaire.png
    - assets/images/online.png
    - assets/images/offline.png
    - assets/images/coeur.png
