name: museum
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.0-22.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/images/Mona_Lisa.jpg

  fonts: 
    - family: Merriweather
      fonts:
        - asset : assets/fonts/Merriweather-Black.ttf
        - asset : assets/fonts/Merriweather-BlackItalic.ttf
        - asset : assets/fonts/Merriweather-Bold.ttf
        - asset : assets/fonts/Merriweather-BoldItalic.ttf
        - asset : assets/fonts/Merriweather-Italic.ttf
        - asset : assets/fonts/Merriweather-Light.ttf
        - asset : assets/fonts/Merriweather-LightItalic.ttf
        - asset : assets/fonts/Merriweather-Regular.ttf